#!/usr/bin/env ruby
#       
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#       Copyright Vincent Reydet

require 'template.class'
require 'config'

@srcDir='src'
genDir="generated"
@tpl = Template.new

def go(genDir,serverConfig)
  #scan files
  Dir[@srcDir+'/**/*'].each do |i|
    print "."
    next if File.directory?(i)
    dirname=File.dirname(i).gsub(@srcDir,'')
    basename=File.basename(i)
    gendirname=genDir+dirname

    #get the generated file content
    @tpl.setServerConfig(serverConfig)
    atplTagMessage="# Generated by atpl - https://github.com/Toubib/atpl\n# "+Time.now.to_s+"\n"
    ret=atplTagMessage+@tpl.process(i)
    #p "*:"+basename+":"+ret

    #write the generated file
    FileUtils.mkdir_p gendirname if !File.exist?(gendirname)
    open(gendirname+'/'+basename,'w') { |f|
      f << ret
    }
  end
  print "\n"
end

#GOGOGOGO
@servers.each_key { |server|
 puts " * "+server
 go(genDir+'/'+server,@servers[server])
}
